basePath: /api/v1
definitions:
  errors.Response:
    properties:
      description:
        type: string
      error:
        type: error
      errorCode:
        type: integer
      header:
        type: string
      statusCode:
        type: integer
      uri:
        type: string
    type: object
host: localhost:9096
info:
  contact:
    email: admin@localhost
    name: API Support
    url: localhost:9096
  description: This is a auth server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: localhost:9096
  title: Auth Service API
  version: "1.0"
paths:
  /authorize:
    get:
      consumes:
      - application/json
      description: Authorize with Auth2
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Response'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Response'
      summary: Authorize
  /token:
    get:
      consumes:
      - application/json
      description: Retrieve auth2 access token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Response'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Response'
      summary: Retrieve access token
swagger: "2.0"
